### ISSUE TITLE
Error in datafile

### ISSUE THREAD

**Issue by polarstern** [QuantLet/QID-1684-MVAsimcibh#1]
bostonh.dat[506, 14] = 11.90\032 - not numeric, the code doesn't run properly.

**Comment by lborke** [comment]
I have checked the code and dataset. Everything runs.
I use Win + R 3.1.1.
I have analyzed the data file. There is a "special character" in the end. My system seems to ignore it. However, I will delete it. Then you can test the Q with this datafile on your machine.

**Comment by polarstern** [comment]
Now everything runs without any errors or warnings.

**Comment by lborke** [comment]
Fine!
Was zu erwarten war.
