### ISSUE TITLE
Datafile should be updated

### ISSUE THREAD

**Issue by polarstern** [QuantLet/QID-1684-MVAsimcibh#3]
Please leave only last version of datafile

**Comment by lborke** [comment]
What do you mean? The only datafile in this repo is the current one, which I have corrected a few days before.

**Comment by polarstern** [comment]
Oh, I thought that you corrected it only at Quantlet and that it was the old version.

**Comment by lborke** [comment]
You can always use the "history" function to check the last changes, independently on the file format:
https://github.com/QuantLet/QID-1684-MVAsimcibh/commits/master/bostonh.dat

**Comment by polarstern** [comment]
Ok, alles klar :-)
